name: Debug Docker Login

on:
  workflow_dispatch:

jobs:
  test-docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Save SA key
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > ${HOME}/key.json
          head -5 ${HOME}/key.json

      - name: Docker login
        run: |
          docker login -u _json_key --password-stdin https://asia-east1-docker.pkg.dev < ${HOME}/key.json