name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "feature" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t gcr.io/oral-flask-ai-app-20250820/flask-app .
